name: permissions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with:
          app_id: 255848
          installation_id: 30702068
          private_key: ${{ secrets.PRIVATE_KEY }}
    
      - name: Checkout local source
        uses: actions/checkout@v3
        
      - name: checkout another repo
        uses: actions/checkout@v3
        with:
          repository: delsauce/private-test
          token: ${{ steps.get_installation_token.outputs.token }}
          path: prvate1
    
    
